# Generated by Django 3.2 on 2022-10-13 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(unique=True)),
                ('duration_in_sec', models.IntegerField(default=30)),
                ('no_question_to_display', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('question', models.TextField(unique=True)),
                ('display_question_on_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_questions', to='grammar.step')),
            ],
        ),
    ]
