# Generated by Django 3.2 on 2022-10-14 16:53

from django.db import migrations, models
import grammar.models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('audio_recording', models.FileField(upload_to=grammar.models.upload_location_activity_images)),
            ],
        ),
    ]
