# Generated by Django 3.2 on 2022-10-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0002_auto_20221009_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='time',
            new_name='duration_in_sec',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='page_numner',
            new_name='page_number',
        ),
    ]
