# Generated by Django 3.2 on 2022-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_rename_question_steps_question_display_question_on_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='step',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
