# Generated by Django 3.2 on 2022-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_alter_recording_audio_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_recording',
            field=models.BinaryField(),
        ),
    ]
